# Generated by Django 3.2.25 on 2024-06-08 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_rename_records_record'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='deleted_at',
        ),
    ]
